name: Deploy To DockerHub And Heroku

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: docker build -t paulbabu05/open-recipe .           
      - run: echo "${{secrets.DOCKERHUB_SECRET}}" | docker login -u paulbabu05 --password-stdin      
      - run: docker push paulbabu05/open-recipe
      
      - run: docker build --tag registry.heroku.com/"${{secrets.HEROKU_APP_NAME}}"/web .
      - run: echo "${{secrets.HEROKU_API_KEY}}" | docker login --username=paulbabu05 registry.heroku.com --password-stdin
      - run: docker push registry.heroku.com/"${{secrets.HEROKU_APP_NAME}}"/web
      - run: heroku container:release web --app "${{secrets.HEROKU_APP_NAME}}"
